apiVersion: v1
kind: Pod
metadata:
  name: javahelloworld.example.com
  labels:
    app: helloworldjava
spec: 
  containers:
  - name: mavenrepo
    image: yuvaraj9908/my-maven-java
    ports:
    - name: java-port
      containerPort: 3001
